[package]
name = "flow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
file = "1.1.2"
#once_cell = "1.10.0"
#hex = "0.4.3"
#fnv = "1.0.6"
state="0.5.2"
