[package]
name = "flow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
file = "1.1.2"
chrono="0.4.19"
ndata="0.1.1"

[[bin]]
name = "flow"
path = "src/main.rs"

[[bin]]
name = "flowb"
path = "src/build.rs"

